import React from "react";
import { Inter } from 'next/font/google';
import Navbar from './component/Navbar';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
// import { Card, Flex, Avatar, Box, Text } from "@radix-ui/themes";



const inter = Inter({ subsets: ['latin'] });



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>  

        {/* <Card style={{ maxWidth: 240 }}>
          <Flex gap="3" align="center">
            <Avatar
              size="3"
              src="https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?&w=64&h=64&dpr=2&q=70&crop=focalpoint&fp-x=0.67&fp-y=0.5&fp-z=1.4&fit=crop"
              radius="full"
              fallback="T"
            />
            <Box>
              <Text as="div" size="2" weight="bold">
                Teodros Girmay
              </Text>
              <Text as="div" size="2" color="gray">
                Engineering
              </Text>
            </Box>
          </Flex>
        </Card> */}

      <div className="flex min-h-screen">
        <div className='w-1/6 h-100 bg-slate-100'>
        <Navbar/>
        </div> 
        <div className='w-10/12 h-100 bg-white'>
       
          {children} 
        </div>
      </div>           
      </Theme>
      </body>
    </html>
  )
}
